### ISSUE TITLE
Dependency Question

### ISSUE THREAD

**Issue by adibbz** [tiboprea/universal-nest-wallets-ssr#1]
Hey @tiboprea! I noticed your back and forth with the @danmt on getting started with  `@danmt/wallet-adapter-angular` and found this repo. 

I've been having some dependency issues and was wondering if you could maybe tell me what versions of these packages you used to get it up and running. Any help would be appreciated! 

```
@danmt/wallet-adapter-angular 
@solana/wallet-adapter-base
@solana/wallet-adapter-wallets
@solana/web3.js
```

**Comment by danmt** [comment]
Hey @adibbz I think these versions should work:

```
"@danmt/wallet-adapter-angular": "^0.1.49",
"@solana/wallet-adapter-base": "^0.6.0",
"@solana/wallet-adapter-wallets": "^0.10.1",
"@solana/web3.js": "^1.29.2",
```

I created a simple [counter app using the wallet-adapter](https://github.com/danmt/counter/commit/a9d32668c91a758198bb67defb845c0ebed5fbbf?diff=unified), I hope that helps. 

Anyway, I'm currently updating the package due to some breaking changes in its deps, which should be ready this weekend and will be easier to build yourself and play with it. I can't promise anything but I'm hoping this package gets officially released by next week.

**Comment by adibbz** [comment]
@danmt sweet thanks man! All good as long as I can get started that's super helpful. Thanks for all your work on this.
